<!-- Base theme - Fluid begins / Début du thème Base - Fluide -->
	<link href="../../theme-base-fluid/css/theme-base-fluid.css" rel="stylesheet" type="text/css" />
	<!--[if IE 7]><link href="../../theme-base-fluid/css/theme-base-fluid-ie7.css" rel="stylesheet" type="text/css" /><![endif]-->
	<!--[if lte IE 6]><link href="../../theme-base-fluid/css/theme-base-fluid-ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
<!-- Base theme - Fluid ends / Fin du thème Base - Fluide -->
