<!-- base theme begins / Début du thème base -->
		<p>Contient normalement le contenu principal de la page et la date de la dernière modification.</p>
		<p lang="en" xml:lang="en">Normally contains the main content of the page and the date the content was last modified.</p>
			<h2>Valeurs implicites importantes / <span lang="en" xml:lang="en">Important default values</span></h2>
			<p><strong>Nota&#160;:</strong> Les valeurs implicites sont pour le CSS base et pas pour le thème actuel.</p>
			<p lang="en" xml:lang="en"><strong>Note:</strong> Default values are for the base CSS and not the current theme.</p>
			<dl lang="en" xml:lang="en">
				<dt><code>cn-centre-col-inner</code>&#160;:</dt>
				<dd>
					<ul>
						<li><code>padding: 1px 5px;</code></li>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
			</dl>
<!-- base theme ends / Fin du thème base -->
