<!-- base theme begins / Début du thème base -->
		<p>Normally contains the main content of the page and the date the content was last modified.</p>
		<p lang="fr" xml:lang="fr">Contient normalement le contenu principal de la page et la date de la dernière modification.</p>
			<h2>Important default values / <span lang="fr" xml:lang="fr">Valeurs implicites importantes</span></h2>
			<p><strong>Note:</strong> Default values are for the base CSS and not the current theme.</p>
			<p lang="fr" xml:lang="fr"><strong>Nota&#160;:</strong> Les valeurs implicites sont pour le CSS base et pas pour le thème actuel.</p>
			<dl>
				<dt><code>cn-centre-col-inner</code>:</dt>
				<dd>
					<ul>
						<li><code>padding: 1px 5px;</code></li>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
			</dl>
<!-- base theme ends / Fin du thème base -->
