<!-- base theme begins / Début du thème base -->
		<h2>Header (Base) / <span lang="fr" xml:lang="fr">En-tête (base)</span></h2>

		<h3>Important default values / <span lang="fr" xml:lang="fr">Valeurs implicites importantes</span></h3>
		<p><strong>Note:</strong> Default values are for the base CSS and not the current theme.</p>
		<p lang="fr" xml:lang="fr"><strong>Nota&#160;:</strong> Les valeurs implicites sont pour le CSS base et pas pour le thème actuel.</p>
		<dl>
			<dt><code>cn-head</code>:</dt>
			<dd>
				<ul>
					<li><code>background: #FFF</code></li>
				</ul>
			</dd>
		</dl>
<!-- base theme ends / Fin du thème base -->
