<!-- base theme begins / Début du thème base -->
		<h2>En-tête (base) / <span lang="en" xml:lang="en">Header (Base)</span></h2>

		<h3>Valeurs implicites importantes / <span lang="en" xml:lang="en">Important default values</span></h3>
		<p><strong>Nota&#160;:</strong> Les valeurs implicites sont pour le CSS base et pas pour le thème actuel.</p>
		<p lang="en" xml:lang="en"><strong>Note:</strong> Default values are for the base CSS and not the current theme.</p>
		<dl lang="en" xml:lang="en">
			<dt><code>cn-head</code>&#160;:</dt>
			<dd>
				<ul>
					<li><code>background: #FFF</code></li>
				</ul>
			</dd>
		</dl>
<!-- base theme ends / Fin du thème base -->
