<!-- Base theme - Fluid begins / Début du thème Base - Fluide -->
		<div id="cn-foot-base">
			<h3>Footer (Base) / <span lang="fr" xml:lang="fr">Pied de page (Base)</span></h3>
			<ul>
				<li>unordered list (<code>ul</code>) first level default appearance / <span lang="fr" xml:lang="fr">liste à puces (<code>ul</code>) premier niveau - apparence par défaut</span>
					<ul>
						<li>unordered list (<code>ul</code>) second level default appearance / <span lang="fr" xml:lang="fr">liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut</span></li>
					</ul>
				</li>
			</ul>
		</div>
<!-- Base theme - Fluid ends / Fin du thème Base - Fluide -->
