<!-- Base theme - Fluid begins / Début du thème Base - Fluide -->
		<div id="cn-head-base">
			<h2>Header (Base)</h2>
			<ul>
				<li>unordered list (<code>ul</code>) first level default appearance
					<ul>
						<li>unordered list (<code>ul</code>) second level default appearance</li>
					</ul>
				</li>
			</ul>
		</div>
<!-- Base theme - Fluid ends / Fin du thème Base - Fluide -->
