<!-- Base theme - Fixed begins / Début du thème Base - Fixe -->
		<div id="cn-head-base">
			<h2>Header (Base) / <span lang="fr" xml:lang="fr">En-tête (Base)</span></h2>
			<ul>
				<li>unordered list (<code>ul</code>) first level default appearance / <span lang="fr" xml:lang="fr">liste à puces (<code>ul</code>) premier niveau - apparence par défaut</span>
					<ul>
						<li>unordered list (<code>ul</code>) second level default appearance / <span lang="fr" xml:lang="fr">liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut</span></li>
					</ul>
				</li>
			</ul>
		</div>
<!-- Base theme - Fixed ends / Fin du thème Base - Fixe -->
