<!-- Base theme - Fixed + Grids begins / Début du thème Base - Fixe + Grilles -->
	<link href="../../theme-base-fixed-grids/css/theme-base-fixed-grids.css" rel="stylesheet" type="text/css />
	<!--[if IE 7]><link href="../../theme-base-fixed-grids/css/theme-base-fixed-grids-ie7.css" rel="stylesheet" type="text/css /><![endif]-->
	<!--[if lte IE 6]><link href="../../theme-base-fixed-grids/css/theme-base-fixed-grids-ie6.css" rel="stylesheet" type="text/css /><![endif]-->
<!-- Base theme - Fixed + Grids ends / Fin du thème Base - Fixe + Grilles -->
