<!-- Base theme - Fixed + Grids begins / Début du thème Base - Fixe + Grilles -->
		<div id="cn-foot-base">
			<h3>Pied de page (Base)</h3>
			<ul>
				<li>liste à puces (<code>ul</code>) premier niveau - apparence par défaut
					<ul>
						<li>liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut</li>
					</ul>
				</li>
			</ul>
		</div>
<!-- Base theme - Fixed + Grids ends / Fin du thème Base - Fixe + Grilles -->
